### ISSUE TITLE
Typos in the main form

### ISSUE THREAD

**Issue by kckst8** [aguacongas/azure-devops-extensions#18]
There are a few typos in the main. ("Boby" should be "Body", "chanhed" should be "changed").  I resolved them in this [in this PR](https://github.com/aguacongas/azure-devops-extensions/pull/17)

#17

**Comment by aguacongas** [comment]
#17 resolved this issue

**Comment by aguacongas** [comment]
@kckst8 Thanks again for your commit, the new version is now deployed on the market place

**Comment by kckst8** [comment]
thank you!!
