### ISSUE TITLE
Loading spinner forever and error in the console. 

### ISSUE THREAD

**Issue by RyanParsley** [aguacongas/azure-devops-extensions#22]
We've just installed this extension and it hangs on a loading state with the following message in the modal:

 "CommitiZen Pull Request by Aguafrommars is taking longer than expected to load.Learn More about this extension, including available support options."

Inspecting the console reveals this error:
```Uncaught TypeError: Cannot read property 'gitPullRequest' of undefined at registerContribution```
I dropped a debugger in context.js
```
const t = VSS.getConfiguration().properties.pullRequest;
    var n;
    const o = ["feat - A new feature", "fix - A bug fix", "docs - Documentation only changes", "style - Changes that not affect the meaning of the code", "refactor - A code change that neither fix a bug nor adds a feature", "perf - A code change that improves performance", "test - Adding missing tests or correcting existing tests", "build - Changes that affect the build system or external dependencies", "ci - Changes to oour CI configuration files ans scripts", "revert - Revert a previous commit"];
    var s;
    const i = t.pullRequestCard.gitPullRequest.completionOptions;
```
In the above, t is defined but does not have a pullRequestCard property. Is there some configuration we need to do to make this work?

**Comment by aguacongas** [comment]
Are you using a GIT repo or an old TFS repo ?

**Comment by RyanParsley** [comment]
It's a git repo.

**Comment by RyanParsley** [comment]
Here's a little more context in hopes that's helpful. 

<img width="1890" alt="Screen Shot 2020-11-19 at 9 53 37 AM" src="https://user-images.githubusercontent.com/58023/99714387-88d1f980-2a73-11eb-9422-b1b57a4aa431.png">

I do notice that the artifactId starts vstfs, I don't know if that is significant. I only know the company to use git to interface with code.

**Comment by aguacongas** [comment]
What's the TFS version ? Is it in premise or online ?

**Comment by RyanParsley** [comment]
Sounds like we're using the online version. Is a version number still applicable in that case?

**Comment by aguacongas** [comment]
extension version 1.0.0.19
