### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by RyanParsley** [aguacongas/azure-devops-extensions#27]
If there's a theme to hook into, that's be ideal, but a little padding around the white area could go a long way to make it not look broken with a dark theme enabled:

<img width="659" alt="Screen Shot 2020-11-24 at 9 13 00 AM" src="https://user-images.githubusercontent.com/58023/100105623-956c9e00-2e35-11eb-92ea-078c36e05f04.png">

**Comment by aguacongas** [comment]
fix in 1.0.0.27
