### ISSUE TITLE
Not working in new PR screen

### ISSUE THREAD

**Issue by nixstrom** [aguacongas/azure-devops-extensions#31]
Azure has rolled out a new PR view. Unfortunately, this has "broken" the extension, so it is no longer possible to merge PRs using CommitiZen.

> Invalid argument value. Parameter name: You must specify a LastMergeSourceCommit to perform this operation.

![image](https://user-images.githubusercontent.com/2905361/107932296-aed93e00-6f7d-11eb-8b89-feb5b36e892f.png)

I am happy to help fixing it, if you could point me in the right direction.

**Comment by aguacongas** [comment]
@nixstrom thanks contribute. I do not have any direction at the moment except checking browser logs and browse google for a solution. But that's js, it's surely not very hard to solve

**Comment by aguacongas** [comment]
fixed in extension version 1.0.0.33

**Comment by nixstrom** [comment]
Excellent! Thanks aguacongas.
