### ISSUE TITLE
CommitiZen extension is bypassing branch policies

### ISSUE THREAD

**Issue by isabr85** [aguacongas/azure-devops-extensions#36]
I have noticed that branch policies are being ignored on PR completion with CommitiZen extension. In my case there are 2 required policies that hasn't passed yet, but CommitiZen completed the PR anyway. I know that there is an option to use Set Auto-Complete button which is great, but I would expect this extension to follow the policies that applied on the branch.

Another issue I have: When I use CommitiZen with Set Auto-Complete option I noticed that the PR title is not getting changed, and it remains as it was before using CommitiZen. Why CommitiZen doesn't change commit title inside the PR? It is important for me because I have a webhook that being triggered when PR is getting updated, but because the title isn't getting changed - webhook not being triggered.

Thanks.

**Comment by aguacongas** [comment]
@isabr85 IMHO if the extension can override the branch policy it's a Azure DevOps issue, the extension use VSS SDK to update request using [`TFS/VersionControl/GitRestClient` service and its method `updatePullRequest`](https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/gitrestclient#updatepullrequest-gitpullrequest--string--number--string-). Do you agree ?

The extension doesn't update the PR title. Again, if you expect a title changed, it's a VSS SDK issue I guess.

**Comment by isabr85** [comment]
@aguacongas 
Thanks for your response, I agree about branch policy override, it should be an issue for Azure devops.
Regarding the PR title that not get change once I click on Complete or Auto-Complete:
I have found inside context.js the Click events of Complete and Auto-Complete buttons, in both cases a `GitPullRequest` object is being initialized with `status`, `completionOptions` and `lastMergeSourceCommit` properties and passed to `updatePullRequest` method. see example below:

```
$("#complete").on("click", function() {
    const error = validateForm();
    if (error) {
        showError(error);
        return;
    }
    hideError();
    VSS.require(["VSS/Service", "TFS/VersionControl/GitRestClient"], function (VSS_Service, TFS_Wit_WebApi) {
        // Get the REST client
        const gitClient = VSS_Service.getCollectionClient(TFS_Wit_WebApi.GitHttpClient2_2);

        const patch = {
            status: 3,
            completionOptions: getCompletionOptions(),
            lastMergeSourceCommit: pr.lastMergeSourceCommit || pr.pullRequestCard.gitPullRequest.lastMergeSourceCommit
        }

        gitClient.updatePullRequest(patch, pr.repositoryId, pr.pullRequestId)
            .then(function() {
                notify();
            }, function(error) {
                showError(error.message || "Unknow exception");
            });
    });            
});
```

According to [Microsoft - GitPullRequest documentation](https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/gitpullrequest?view=azdevops-ext-latest) you can set  `title` and `description` properties as well with the commit title and commit body, and this should update PR title and description. Obviously it should be done in both Complete and Auto-Complete events.

Do you agree?

**Comment by aguacongas** [comment]
I do, can you fix and submit a PR ?

**Comment by isabr85** [comment]
Will do.
Is that possible also to make the commit consistent with Azure PR completion pattern?
When I complete a PR without commitiZen, the created commit contains a prefix of `Merged PR 12345: ` with commitiZen this prefix is not exists. I do rely on this prefix pattern. Can we add that as well?

**Comment by aguacongas** [comment]
No, in that case the extension is useless. This extension is made to update
the commit message with the CommitZen pattern, if you want the
default commit message you don't need it.
